# yaml-language-server: $schema=https://raw.githubusercontent.com/mui/mui-toolpad/v0.1.50/docs/schemas/v1/definitions.json#properties/Page

apiVersion: v1
kind: page
spec:
  title: stoppoints
  content:
    - component: PageRow
      name: pageRow11
      children:
        - component: PageColumn
          name: pageColumn11
          layout:
            columnSize: 1
          children:
            - component: PageRow
              name: pageRow2
              props:
                justifyContent: start
              children:
                - component: Image
                  name: image1
                  layout:
                    columnSize: 0.13695090439276486
                    verticalAlign: end
                  props:
                    src: https://iili.io/J551oP4.png
                    width: 70
                    height: 40
                    loading: false
                - component: Text
                  name: stpointpagehead
                  layout:
                    columnSize: 1.8630490956072352
                    horizontalAlign: center
                  props:
                    value: Stop Points management page
                    variant: h4
                    mode: text
            - component: PageRow
              name: pageRow3
              props:
                justifyContent: start
              children:
                - component: Text
                  name: stoppointtabhead
                  layout:
                    columnSize: 2.030188679245283
                    horizontalAlign: center
                  props:
                    value: Stop Points List
                    variant: h5
                - component: Button
                  name: refetchbut
                  layout:
                    columnSize: 0.4830188679245283
                    horizontalAlign: center
                  props:
                    size: small
                    content: Refresh
                    color: primary
                    variant: outlined
                    onClick:
                      $$jsExpressionAction: queStopPointFindAll.refetch()
                    loading: false
                    fullWidth: true
                - component: Button
                  name: delstpobut
                  layout:
                    columnSize: 0.4867924528301887
                  props:
                    content: Delete Stop Point
                    color: error
                    size: small
                    onClick:
                      $$jsExpressionAction: |-
                        //await deleteCustomer.call();
                        getCustomers.refetch();
                    fullWidth: true
                    disabled:
                      $$jsExpression: |
                        !customersGrid.selection
                    sx:
                      background: red
                      fontSize: 9px
                - component: Button
                  name: addstpobut
                  layout:
                    columnSize: 0.5584415584415584
                  props:
                    content: Add Stop Point
                    size: small
                    onClick:
                      $$jsExpressionAction: >+
                        contCreateStopPoint.visible =
                        contCreateStopPoint.visible === false ? true : false;

                    fullWidth: true
                    disabled:
                      $$jsExpression: |
                        !customersGrid.selection
            - component: DataGrid
              name: dataStopPointGrid
              props:
                rows:
                  $$jsExpression: |
                    queStopPointFindAll.data
                columns:
                  - field: id
                    type: number
                  - field: name
                    type: string
                    width: 141
                  - field: description
                    type: json
                  - field: active
                    type: boolean
                  - field: x
                    type: number
                  - field: y
                    type: number
                  - field: stopId
                    type: json
                hideToolbar: true
                loading: false
                rowsSource: prop
            - component: Text
              name: stpoupdhead
              layout:
                columnSize: 1
                horizontalAlign: start
              props:
                value: Update Stop Point
                variant: h5
            - component: Form
              name: updateStopPointForm
              layout:
                columnSize: 1
              props:
                onSubmit:
                  $$jsExpressionAction: |-
                    //await updateStopPoint.call();
                    //getCustomers.refetch();
                    await actUpdStopPointForm.call();
                    queStopPointFindAll.refetch();
                submitButtonText: null
                hasResetButton: false
                hideControls: false
                formControlsFullWidth: false
                formControlsAlign: end
              children:
                - component: PageRow
                  name: pageRow5
                  props:
                    justifyContent: start
                  children:
                    - component: TextField
                      name: idsp
                      layout:
                        columnSize: 1
                      props:
                        label: ID
                        disabled: false
                        fullWidth: true
                        isRequired: true
                        name: idsp
                        placeholder: 111
                        defaultValue:
                          $$jsExpression: |
                            dataStopPointGrid.selection.id
                    - component: TextField
                      name: namesp
                      layout:
                        columnSize: 1
                      props:
                        label: Name
                        disabled: false
                        fullWidth: true
                        isRequired: true
                        name: namesp
                        placeholder: Sveti Vlas
                        defaultValue:
                          $$jsExpression: |
                            dataStopPointGrid.selection.name
                    - component: TextField
                      name: xlat
                      layout:
                        columnSize: 1
                      props:
                        label: x (lat)
                        disabled: false
                        fullWidth: true
                        isRequired: true
                        name: xlat
                        placeholder: 32.628
                        defaultValue:
                          $$jsExpression: |
                            dataStopPointGrid.selection.x
                    - component: TextField
                      name: xlong
                      layout:
                        columnSize: 1
                      props:
                        label: x (long)
                        disabled: false
                        fullWidth: true
                        isRequired: true
                        name: xlong
                        placeholder: 55.75
                        defaultValue:
                          $$jsExpression: |
                            dataStopPointGrid.selection.y

                - component: PageRow
                  name: pageRow6
                  props:
                    justifyContent: start
                  children:
                    - component: TextField
                      name: descrsp
                      layout:
                        columnSize: 1
                      props:
                        label: Description
                        disabled: false
                        fullWidth: true
                        isRequired: true
                        name: descrsp
                        placeholder: please add a description
                        defaultValue:
                          $$jsExpression: |
                            dataStopPointGrid.selection.description
                    - component: TextField
                      name: refstopid
                      layout:
                        columnSize: 1
                      props:
                        label: Stop ID
                        disabled: false
                        fullWidth: true
                        isRequired: true
                        name: refstopid
                        placeholder: 444
                        defaultValue:
                          $$jsExpression: |
                            dataStopPointGrid.selection.stopId
                    # - component: PageColumn
                    #   name: pageColumn8
                    #   layout:
                    #     columnSize: 1.5271317829457365
                    #   children:
                    #     - component: TextField
                    #       name: xlat
                    #       layout:
                    #         columnSize: 0.4
                    #       props:
                    #         label: x (lat)
                    #         disabled: false
                    #         fullWidth: true
                    #         isRequired: true
                    #         name: xlat
                    #         placeholder: 32.628
            - component: Container
              name: contCreateStopPoint
              props:
                visible: false
              children:
                - component: Text
                  name: stpocrehead
                  layout:
                    columnSize: 1
                    horizontalAlign: start
                  props:
                    value: Create Stop Point
                    variant: h5
                - component: Form
                  name: createStopPointForm
                  layout:
                    columnSize: 1
                  props:
                    onSubmit:
                      $$jsExpressionAction: |
                        let value = createStopPointForm.value
                        actCreateStopPointForm.call(value)
                        //getCustomers.refetch();
                    submitButtonText: Create
                    hasResetButton: false
                    hideControls: false
                    formControlsFullWidth: false
                    formControlsAlign: end
                  children:
                    - component: PageRow
                      name: pageRow1
                      props:
                        justifyContent: start
                      children:
                        - component: TextField
                          name: idsp1
                          layout:
                            columnSize: 1
                          props:
                            label: ID
                            disabled: false
                            fullWidth: true
                            isRequired: true
                            name: idsp
                            placeholder: 111
                            # defaultValue:
                            #   $$jsExpression: |
                            #     dataStopPointGrid.selection.id
                        - component: TextField
                          name: namesp1
                          layout:
                            columnSize: 1
                          props:
                            label: Name
                            disabled: false
                            fullWidth: true
                            isRequired: true
                            name: namesp
                            placeholder: Sveti Vlas
                            # defaultValue:
                            #   $$jsExpression: |
                            #     dataStopPointGrid.selection.name
                        - component: TextField
                          name: xlat1
                          layout:
                            columnSize: 1
                          props:
                            label: x (lat)
                            disabled: false
                            fullWidth: true
                            isRequired: true
                            name: xlat
                            placeholder: 32.628
                            # defaultValue:
                            #   $$jsExpression: |
                            #     dataStopPointGrid.selection.x
                        - component: TextField
                          name: xlong1
                          layout:
                            columnSize: 1
                          props:
                            label: x (long)
                            disabled: false
                            fullWidth: true
                            isRequired: true
                            name: xlong
                            placeholder: 55.75
                            # defaultValue:
                            #   $$jsExpression: |
                            #     dataStopPointGrid.selection.y
                    - component: PageRow
                      name: pageRow4
                      props:
                        justifyContent: start
                      children:
                        - component: TextField
                          name: descrsp1
                          layout:
                            columnSize: 1
                          props:
                            label: Description
                            disabled: false
                            fullWidth: true
                            isRequired: true
                            name: descrsp
                            placeholder: please add a description
                            defaultValue:
                            $$jsExpression: |
                              dataStopPointGrid.selection.description
                        - component: TextField
                          name: refstopid1
                          layout:
                            columnSize: 1
                          props:
                            label: Stop ID
                            disabled: false
                            fullWidth: true
                            isRequired: true
                            name: refstopid
                            placeholder: 444

  queries:
    - name: queStopPointFindAll
      mode: query
      query:
        kind: rest
        url: http://localhost:4995/api/stop-point/find-all?api_key=KrtKNkLNGcwKQ56la4jcHwxF
        searchParams: []
        headers: []
        method: GET
        transform: |-

          return data.map(elem => {
            const { persistent, point, ...rest } = elem;
            const combined = { ...persistent, ...point };
            const result = { ...combined, ...rest };
            return result;
          });
        transformEnabled: true
    - name: actUpdStopPointForm
      mode: mutation
      query:
        kind: local
        function: functions2.ts#updateStopPointForm
      parameters:
        - name: id
          value:
            $$jsExpression: |
              updateStopPointForm.value
        - name: values
          value:
            $$jsExpression: |
              updateStopPointForm.value
    - name: actCreateStopPointForm
      mode: mutation
      query:
        kind: local
        function: functions2.ts#createStopPointForm
      parameters:
        - name: values
          value:
            $$jsExpression: |
              createStopPointForm.value
  display: shell
