# yaml-language-server: $schema=https://raw.githubusercontent.com/mui/mui-toolpad/v0.1.43/docs/schemas/v1/definitions.json#properties/Page

apiVersion: v1
kind: page
spec:
  title: stoppoints
  content:
    - component: PageRow
      name: pageRow11
      children:
        - component: PageColumn
          name: pageColumn11
          layout:
            columnSize: 1
          children:
            - component: PageRow
              name: pageRow2
              props:
                justifyContent: start
              children:
                - component: Image
                  name: image1
                  layout:
                    columnSize: 0.13695090439276486
                    verticalAlign: end
                  props:
                    src: https://iili.io/J551oP4.png
                    width: 70
                    height: 40
                    loading: false
                - component: Text
                  name: stpointpagehead
                  layout:
                    columnSize: 1.8630490956072352
                    horizontalAlign: center
                  props:
                    value: Stop's management page
                    variant: h4
                    mode: text
            - component: PageRow
              name: pageRow3
              props:
                justifyContent: start
              children:
                - component: Text
                  name: stoppointtabhead
                  layout:
                    columnSize: 2.030188679245283
                    horizontalAlign: center
                  props:
                    value: Stop's List
                    variant: h5
                - component: Button
                  name: refetchbut
                  layout:
                    columnSize: 0.4830188679245283
                    horizontalAlign: center
                  props:
                    size: small
                    content: Refresh
                    color: primary
                    variant: outlined
                    onClick:
                      $$jsExpressionAction: getCustomers.refetch()
                    loading: false
                    fullWidth: true
                - component: Button
                  name: delstpobut
                  layout:
                    columnSize: 0.4867924528301887
                  props:
                    content: Delete Stop Point
                    size: small
                    onClick:
                      $$jsExpressionAction: >+
                        //await deleteCustomer.call();


                        contCreateStop.visible = contCreateStop.visible === false ? true : false;

                    fullWidth: true
                    disabled:
                      $$jsExpression: |
                        !customersGrid.selection
            - component: DataGrid
              name: dataStopGrid
              props:
                rows:
                  $$jsExpression: |
                    queStopFindAll.data
                columns:
                  - field: id
                    type: number
                  - field: name
                    type: string
                  - field: description
                    type: json
                  - field: creator
                    type: number
                  - field: locales
                    type: json
                  - field: active
                    type: boolean
                  - field: number
                    type: number
                  - field: abbreviation
                    type: string
                  - field: address
                    type: string
                  - field: depot
                    type: boolean
                hideToolbar: true
                loading: false
                rowsSource: prop
            - component: Text
              name: stpoupdhead
              layout:
                columnSize: 1
                horizontalAlign: start
              props:
                value: Update Stop
                variant: h5
            - component: Form
              name: updateStopForm
              layout:
                columnSize: 1
              props:
                onSubmit:
                  $$jsExpressionAction: |-
                    //await updateStopPoint.call();
                    //getCustomers.refetch();
                    actUpdStopForm.call()
                    queStopFindAll.refetch()
                submitButtonText: null
                hasResetButton: false
                hideControls: false
                formControlsFullWidth: false
                formControlsAlign: end
              children:
                - component: PageRow
                  name: pageRow5
                  props:
                    justifyContent: start
                  children:
                    - component: TextField
                      name: ids
                      layout:
                        columnSize: 1
                      props:
                        label: ID
                        disabled: false
                        fullWidth: true
                        isRequired: true
                        name: ids
                        placeholder: 111
                        defaultValue:
                          $$jsExpression: |
                            dataStopGrid.selection.id
                    - component: TextField
                      name: names
                      layout:
                        columnSize: 1
                      props:
                        label: Name
                        disabled: false
                        fullWidth: true
                        isRequired: true
                        name: names
                        placeholder: Sveti Vlas
                        defaultValue:
                          $$jsExpression: |
                            dataStopGrid.selection.name
                    - component: TextField
                      name: abbr
                      layout:
                        columnSize: 1
                      props:
                        label: abbr
                        disabled: false
                        fullWidth: true
                        isRequired: true
                        name: abbr
                        placeholder: 32.628
                        defaultValue:
                          $$jsExpression: |
                            dataStopGrid.selection.abbreviation
                    - component: TextField
                      name: number
                      layout:
                        columnSize: 1
                      props:
                        label: number
                        disabled: false
                        fullWidth: true
                        isRequired: false
                        name: number
                        placeholder: 55.75
                        defaultValue:
                          $$jsExpression: |
                            dataStopPointGrid.selection.y
                - component: PageRow
                  name: pageRow6
                  props:
                    justifyContent: start
                  children:
                    - component: TextField
                      name: descr
                      layout:
                        columnSize: 1
                      props:
                        label: Description
                        disabled: false
                        fullWidth: true
                        isRequired: true
                        name: descrs
                        placeholder: please add a description
                        defaultValue:
                          $$jsExpression: |
                            dataStopPointGrid.selection.description
                    - component: TextField
                      name: address
                      layout:
                        columnSize: 1
                      props:
                        label: Address
                        disabled: false
                        fullWidth: true
                        isRequired: true
                        name: address
                        placeholder: 444
                        defaultValue:
                          $$jsExpression: |
                            dataStopGrid.selection.address
            - component: Container
              name: contCreateStop
              props:
                visible: false
              children:
                - component: Text
                  name: stpocrehead
                  layout:
                    columnSize: 1
                    horizontalAlign: start
                  props:
                    value: Create Stop
                    variant: h5
                - component: Form
                  name: createStopForm
                  layout:
                    columnSize: 1
                  props:
                    onSubmit:
                      $$jsExpressionAction: |
                        let value = createStopForm.value
                        actCreateStopForm.call(value)
                        //getCustomers.refetch();
                    submitButtonText: Create
                    hasResetButton: false
                    hideControls: false
                    formControlsFullWidth: false
                    formControlsAlign: end
                  children:
                    - component: PageRow
                      name: pageRow1
                      props:
                        justifyContent: start
                      children:
                        - component: TextField
                          name: ids1
                          layout:
                            columnSize: 1
                          props:
                            label: ID
                            disabled: false
                            fullWidth: true
                            isRequired: true
                            name: ids
                            placeholder: 111
                        - component: TextField
                          name: names1
                          layout:
                            columnSize: 1
                          props:
                            label: Name
                            disabled: false
                            fullWidth: true
                            isRequired: true
                            name: names
                            placeholder: Sveti Vlas
                        - component: TextField
                          name: abbr1
                          layout:
                            columnSize: 1
                          props:
                            label: abbr
                            disabled: false
                            fullWidth: true
                            isRequired: true
                            name: abbr
                            placeholder: 32.628
                        - component: TextField
                          name: number1
                          layout:
                            columnSize: 1
                          props:
                            label: number
                            disabled: false
                            fullWidth: true
                            isRequired: true
                            name: number
                            placeholder: 55.75
                    - component: PageRow
                      name: pageRow4
                      props:
                        justifyContent: start
                      children:
                        - component: TextField
                          name: descrs1
                          layout:
                            columnSize: 1
                          props:
                            label: Description
                            disabled: false
                            fullWidth: true
                            isRequired: true
                            name: descrs
                            placeholder: please add a description
                            defaultValue:
                              $$jsExpression: |
                                dataStopPointGrid.selection.description
                        - component: TextField
                          name: address1
                          layout:
                            columnSize: 1
                          props:
                            label: Address
                            disabled: false
                            fullWidth: true
                            isRequired: true
                            name: address
                            placeholder: 444
  queries:
    - name: actStopFindAll
      mode: mutation
      query:
        kind: rest
        url: http://localhost:4995/api/stop/find-all
        searchParams: []
        headers: []
        method: GET
    - name: queStopFindAll
      mode: query
      query:
        kind: rest
        url: http://localhost:4995/api/stop/find-all
        searchParams: []
        headers: []
        method: GET
        transform: >-
          //return Object.entries(data)

          //const originalArray = data;

          //const transformedArray = originalArray.map(obj => Object.entries(obj));

          //return transformedArray;

          return data.map(elem => {  const persistent = elem.persistent; const copy = { ...persistent, ...elem }; delete copy.persistent; return copy; })
        transformEnabled: true
    - name: actStopPointEdit
      mode: mutation
      query:
        kind: rest
        url: http://localhost:4995/api/stop-point/edit
        searchParams: []
        headers: [{ name: Content-Type, value: application/json }]
        method: PUT
        transformEnabled: false
        body:
          kind: raw
          content: |-
            {
                "persistent": {
                    "id": 1,
                    "name": "New Point ACT 232",
                    "description": null,
                    "creator": 100,
                    "locales": [],
                    "active": true
                },
                "number": 1,
                "point": {
                    "x": 35.6277423,
                    "y": 58.7502455
                },
                "stopId": 12
            }
          contentType: application/json
    - name: actUpdStopForm
      mode: mutation
      query:
        kind: local
        function: functions2.ts#updateStopForm
      parameters:
        - name: values
          value:
            $$jsExpression: |
              updateStopForm.value
    - name: actStopPointFindAll
      mode: mutation
      query:
        kind: rest
        url: http://localhost:4995/api/stop-point/find-all
        searchParams: []
        headers: []
        method: GET
    - name: actCreateStopForm
      mode: mutation
      query:
        kind: local
        function: functions2.ts#createStopForm
      parameters:
        - name: values
          value:
            $$jsExpression: |
              createStopForm.value
  display: shell
